model_args:
    n_layers: 2
    n_heads: 2
    encode_dim: 128
    dropout: 0.1
    seed: 42
    batch: 64
    learning_rate: 0.0001
    epochs: 10
    mlm_prob: 0.2
    max_len: 50
    is_save: 0
    is_debug: 0
    gpu_index: 0

    save_path: model/