model_args:
    n_layers: 1
    n_heads: 1              # 1 is the same as 2
    encode_dim: 64
    dropout: 0.0
    seed: 42
    batch: 100
    learning_rate: 0.001
    epochs: 50              # 50 is good
    mlm_prob: 0.4           
    max_len: 60             # 100 will be better
    is_save: 0
    is_debug: 0
    gpu_index: 1
    negative_samples: 0
    label_smoothing: 0.0
    save_path: model/

